### PR TITLE
Updated expired api

### PR DESCRIPTION
**Pull request by jacastro023**

### CODE REVIEW

**Review by Aleshsparrow — APPROVED** [review]

**Comment by Aleshsparrow** [comment]
Hey Jose, hope you're well. Happy new year!!!

**Comment by jacastro023** [comment]
Hey man, happy new year to you too. Hope you doing well too. Trying to get
my things updated.

**Comment by Aleshsparrow** [comment]
Cool cool my guy. Did you find something yet?

**Comment by jacastro023** [comment]
Not yet, working on making a new portfolio and resume right now. How about
you? What are you up to these days?

**Comment by Aleshsparrow** [comment]
Bro forget all that portfolio shit bro, you have to put some real life work experience on your resume or those recruiters won't even look at you. I went into data analytics, I work as a data analyst/data engineer now bro.

You still have my number? I changed my phone.
But if you don't, here it is: 8722035491.
Text me bro.

**Pull request merged**
